2025-09-19 08:58:53,415 INFO    MainThread:19904 [wandb_setup.py:_flush():80] Current SDK version is 0.21.0
2025-09-19 08:58:53,415 INFO    MainThread:19904 [wandb_setup.py:_flush():80] Configure stats pid to 19904
2025-09-19 08:58:53,415 INFO    MainThread:19904 [wandb_setup.py:_flush():80] Loading settings from C:\Users\Rene\.config\wandb\settings
2025-09-19 08:58:53,415 INFO    MainThread:19904 [wandb_setup.py:_flush():80] Loading settings from G:\Studium\WF Machine Learning\Projekt - Kopie\wandb\settings
2025-09-19 08:58:53,415 INFO    MainThread:19904 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-09-19 08:58:53,415 INFO    MainThread:19904 [wandb_init.py:setup_run_log_directory():703] Logging user logs to .\wandb\run-20250919_085853-7urbcj8e\logs\debug.log
2025-09-19 08:58:53,415 INFO    MainThread:19904 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to .\wandb\run-20250919_085853-7urbcj8e\logs\debug-internal.log
2025-09-19 08:58:53,415 INFO    MainThread:19904 [wandb_init.py:init():830] calling init triggers
2025-09-19 08:58:53,415 INFO    MainThread:19904 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-09-19 08:58:53,416 INFO    MainThread:19904 [wandb_init.py:init():871] starting backend
2025-09-19 08:58:53,649 INFO    MainThread:19904 [wandb_init.py:init():874] sending inform_init request
2025-09-19 08:58:53,704 INFO    MainThread:19904 [wandb_init.py:init():882] backend started and connected
2025-09-19 08:58:53,704 INFO    MainThread:19904 [wandb_init.py:init():953] updated telemetry
2025-09-19 08:58:53,735 INFO    MainThread:19904 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-09-19 08:58:54,666 INFO    MainThread:19904 [wandb_init.py:init():1029] starting run threads in backend
2025-09-19 08:58:54,943 INFO    MainThread:19904 [wandb_run.py:_console_start():2458] atexit reg
2025-09-19 08:58:54,944 INFO    MainThread:19904 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-09-19 08:58:54,944 INFO    MainThread:19904 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-09-19 08:58:54,944 INFO    MainThread:19904 [wandb_run.py:_redirect():2398] Redirects installed.
2025-09-19 08:58:54,956 INFO    MainThread:19904 [wandb_init.py:init():1075] run started, returning control to user process
2025-09-19 08:58:54,958 INFO    MainThread:19904 [wandb_watch.py:_watch():70] Watching
2025-09-19 08:58:58,987 INFO    MainThread:19904 [wandb_run.py:_config_callback():1363] config_cb None None {'model_name': 'gru', 'input_size': 207, 'model_params': {'hidden_sizes': [128, 64, 32], 'dropout_rate': 0.5}, 'learning_rate': 0.0001, 'weight_decay': 0.0001, 'class_balancing_strategy': 'weighted_loss', 'class_weights': "tensor([1.9680, 2.1546, 1.3022, 2.4165, 1.3996, 0.3193], device='cuda:0')"}
2025-09-19 08:59:54,822 INFO    MsgRouterThr:19904 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-09-19 08:59:55,979 ERROR   MainThread:19904 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 2379, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\interface\interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
2025-09-19 08:59:55,985 ERROR   MainThread:19904 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 2379, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\interface\interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
2025-09-19 08:59:55,985 ERROR   MainThread:19904 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 2379, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\interface\interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "G:\Studium\WF Machine Learning\Projekt - Kopie\.venv\lib\site-packages\wandb\sdk\lib\sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionAbortedError: [WinError 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
